DROP TABLE IF EXISTS Patient CASCADE;
DROP TABLE IF EXISTS Child CASCADE;
DROP TABLE IF EXISTS City CASCADE;
DROP TABLE IF EXISTS Hospital CASCADE;
DROP TABLE IF EXISTS Doctor CASCADE;
DROP TABLE IF EXISTS Event CASCADE;
DROP TABLE IF EXISTS doctor_patient CASCADE;